ALTER TABLE switches
    ADD COLUMN IF NOT EXISTS supports_radius_vlan BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS supports_coa BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS supports_ssh_enforcement BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS supports_snmp_write BOOLEAN NOT NULL DEFAULT FALSE;

