ALTER TABLE switches
    ADD COLUMN IF NOT EXISTS snmp_version TEXT NOT NULL DEFAULT '2c',
    ADD COLUMN IF NOT EXISTS snmp_community TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS snmp_port INTEGER NOT NULL DEFAULT 161,
    ADD COLUMN IF NOT EXISTS snmp_timeout_ms INTEGER NOT NULL DEFAULT 2000,
    ADD COLUMN IF NOT EXISTS snmp_retries INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS last_polled_at TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS last_error TEXT NOT NULL DEFAULT '';
