ALTER TABLE switches
    ADD COLUMN IF NOT EXISTS ssh_username TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS ssh_password TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS ssh_port INTEGER NOT NULL DEFAULT 22;
