package main

import (
	"context"
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"
	"time"

	"nac/internal/config"
	"nac/internal/database"
	switchrepository "nac/internal/repository/switchasset"
)

func main() {
	var (
		secret              string
		output              string
		timeout             time.Duration
		requireSwitchSecret bool
	)

	flag.StringVar(&secret, "secret", "", "Fallback RADIUS shared secret when a switch does not define radius_secret")
	flag.StringVar(&output, "output", "", "Optional output file path")
	flag.DurationVar(&timeout, "timeout", 10*time.Second, "DB connect timeout")
	flag.BoolVar(&requireSwitchSecret, "require-switch-secret", false, "Fail if any switch is missing radius_secret")
	flag.Parse()

	secret = strings.TrimSpace(secret)

	cfg, err := config.Load()
	if err != nil {
		fail(err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), timeout)
	defer cancel()

	pool, err := database.NewPostgresPool(ctx, cfg.Postgres)
	if err != nil {
		fail(err)
	}
	defer pool.Close()

	repo := switchrepository.NewPostgresRepository(pool)
	switches, err := repo.ListEnabledSNMP(ctx)
	if err != nil {
		fail(err)
	}

	sort.Slice(switches, func(i, j int) bool {
		return switches[i].ManagementIP < switches[j].ManagementIP
	})

	var builder strings.Builder
	builder.WriteString("# Generated by nac-radius-clients\n")
	builder.WriteString("# Do not edit manually.\n\n")
	for _, asset := range switches {
		ip := strings.TrimSpace(asset.ManagementIP)
		name := sanitizeClientName(asset.Name, ip)
		if ip == "" || name == "" {
			continue
		}
		clientSecret := strings.TrimSpace(asset.RadiusSecret)
		if clientSecret == "" {
			if requireSwitchSecret {
				fail(fmt.Errorf("switch %s (%s) is missing radius_secret", asset.Name, ip))
			}
			clientSecret = secret
		}
		if clientSecret == "" {
			fail(fmt.Errorf("switch %s (%s) is missing radius_secret and no --secret fallback was provided", asset.Name, ip))
		}

		builder.WriteString(fmt.Sprintf("client %s {\n", name))
		builder.WriteString(fmt.Sprintf("    ipaddr = %s\n", ip))
		builder.WriteString(fmt.Sprintf("    secret = %s\n", clientSecret))
		builder.WriteString(fmt.Sprintf("    shortname = %s\n", name))
		builder.WriteString("}\n\n")
	}

	content := builder.String()
	if output == "" {
		fmt.Print(content)
		return
	}

	if err := os.WriteFile(output, []byte(content), 0644); err != nil {
		fail(err)
	}
}

func sanitizeClientName(name, fallback string) string {
	value := strings.TrimSpace(name)
	if value == "" {
		value = fallback
	}
	value = strings.ToLower(value)
	replacer := strings.NewReplacer(".", "-", ":", "-", "/", "-", " ", "-", "_", "-")
	value = replacer.Replace(value)
	value = strings.Trim(value, "-")
	return value
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err.Error())
	os.Exit(1)
}
